#!/usr/bin/env node

const readline = require("readline");
const { nextInput, close } = require("./cliHelpers");
const { getStateReducer } = require("./state");
const { add, quit, show, flush, play } = require("./actions");

let _state = {
  albums: [],
  shouldQuit: false,
  nextOutput: false
};

const stateReducer = getStateReducer({
  add,
  quit,
  show,
  flush,
  play
});

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const CMD_ADD = "add";
const CMD_QUIT = "quit";
const CMD_PLAY = "play";
const CMD_SHOW = "show";
const COMMANDS = [CMD_ADD, CMD_QUIT, CMD_PLAY, CMD_SHOW];

const run = async () => {
  rl.write("\nWelcome to your music collection!\n");

  while (!_state.shouldQuit) {
    try {
      let input = await nextInput(COMMANDS, rl);
      let nextAction = { type: input.cmd, payload: input.args };

      _state = await stateReducer(_state, nextAction);

      if (_state.nextOutput) {
        rl.write(`\n${_state.nextOutput}\n`);
        _state = await stateReducer(_state, { type: "flush" });
      }
    } catch (e) {
      console.error("Error encontered while getting user input:", e);
    }
  }

  rl.write("\nGood Bye!\n");
  rl.close();
};

run();
