#!/usr/bin/env node

const readline = require("readline");
const { nextInput, close } = require("./cliHelpers");

const _state = {
  songs: [],
  shouldQuit: false
};

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const CMD_ADD = "add";
const CMD_QUIT = "quit";
const CMD_PLAY = "play";
const CMD_SHOW = "show";
const COMMANDS = [CMD_ADD, CMD_QUIT, CMD_PLAY, CMD_SHOW];

const run = async () => {
  while (!_state.shouldQuit) {
    let cmd;
    let args;

    try {
      ({ cmd, args } = await nextInput(COMMANDS, rl));
    } catch (e) {
      console.error("Error encontered while getting user input:", e);
    }

    console.log({ cmd, args });

    if (cmd === "quit") {
      _state.shouldQuit = true;
      rl.close();
    }
  }
};

run();
